#!/bin/bash

docker run --rm -it \
  -v ./:/workdir \
  -e TEMPLATECONF=/workdir/meta-opendsp/conf \
  --workdir=/workdir \
  crops/poky \
  /bin/bash -c "source poky/oe-init-build-env && exec /bin/bash -i"
