#!/bin/bash

# Check if all parameters are provided
if [ $# -ne 3 ]; then
    echo "Usage: $0 <device> <device_partition> <partition_number>"
    echo "Example 1: $0 sda sda3 3"
    echo "Example 2: $0 mmcblk0 mmcblk0p3 3"
    exit 1
fi

# Assign input parameters to variables
USER_DATA_DEVICE=$1
USER_DATA_DEVICE_PARTITION=$2
USER_DATA_PARTITION_NUMBER=$3

# Stop services
echo "Stopping services..."
systemctl stop opendsp
systemctl stop smb
systemctl stop nmb
sleep 5

# Unmount data directory
echo "Unmounting data directory..."
umount -v /home/opendsp/data/

# Resize partition
# maybe run e2fsck before just to make sure everything is ok?
e2fsck -p -f /dev/${USER_DATA_DEVICE_PARTITION}
echo "Resizing partition..."
parted /dev/${USER_DATA_DEVICE} <<EOF
resizepart
${USER_DATA_PARTITION_NUMBER}
-16M
q
EOF

# Check and resize filesystem
echo "Checking and resizing filesystem..."
e2fsck -p -f /dev/${USER_DATA_DEVICE_PARTITION}
resize2fs /dev/${USER_DATA_DEVICE_PARTITION}

echo "Done! Press enter to reboot your machine..."
read

# Final cleanup and reboot
mount -o remount,rw /
rm /usr/bin/userdata_resize
rm -r /home/opendsp/data/lost+found
mount -o remount,ro /
shutdown -r now
